
MCU = atmega32u4

F_CPU = 16000000

ARCH = AVR8

F_USB = $(F_CPU)

OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT

OPT_DEFS += -DBOOTLOADER_SIZE=4096

BOOTLOADER = atmel-dfu

BOOTMAGIC_ENABLE ?= yes	
MOUSEKEY_ENABLE ?= yes	
EXTRAKEY_ENABLE ?= yes
RGBLIGHT_ENABLE ?= yes
ENCODER_ENABLE = yes
OLED_DRIVER_ENABLE = yes	
VIA_ENABLE = yes
#VIAL_ENABLE = yes
#VIAL_INSECURE = yes
#VIAL_ENCODERS_ENABLE = yes
#CONSOLE_ENABLE ?= no	
#COMMAND_ENABLE ?= no    
#SLEEP_LED_ENABLE ?= no  
NKRO_ENABLE ?= yes		
#BACKLIGHT_ENABLE ?= no  
LTO_ENABLE = yes